---
- job:
    name: ansible-role-zookeeper
    run: tests/playbooks/run.yaml
    roles:
      - zuul: windmill/ansible-role-zookeeper

- job:
    name: ansible-role-zookeeper-ubuntu-bionic
    parent: ansible-role-zookeeper
    nodeset: ubuntu-bionic

- project:
    templates:
      - windmill-jobs-bionic
    check:
      jobs:
        - ansible-role-zookeeper-ubuntu-bionic
        - tox-linters
    gate:
      jobs:
        - ansible-role-zookeeper-ubuntu-bionic
        - tox-linters
